import { colors } from '@/shared/styles/theme';

export const productCardStyles = {
  card: {
    backgroundColor: colors.white,
    borderRadius: colors.radiusLg,
    padding: '1.25rem',
    boxShadow: colors.shadowSm,
    position: 'relative',
    transition: colors.transition,
    border: `1px solid ${colors.grayLight}`,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  newBadge: {
    position: 'absolute',
    top: '16px',
    left: '16px',
    backgroundColor: colors.blueAccent,
    color: colors.white,
    padding: '0.35rem 0.85rem',
    borderRadius: colors.radiusFull,
    fontSize: '0.75rem',
    fontWeight: '700',
    zIndex: 2,
    boxShadow: colors.shadowSm,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  heartButton: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(4px)',
    borderRadius: '50%',
    width: '36px',
    height: '36px',
    border: 'none',
    cursor: 'pointer',
    color: colors.grayDark,
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: colors.transition,
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
  },
  imageContainer: {
    width: '100%',
    aspectRatio: '1',
    marginBottom: '1rem',
    borderRadius: colors.radiusMd,
    overflow: 'hidden',
    backgroundColor: colors.grayLight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    objectFit: 'contain',
    transition: 'transform 0.5s ease',
  },

  typeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.35rem',
    padding: '0.35rem 0.75rem',
    borderRadius: colors.radiusFull,
    fontSize: '0.75rem',
    fontWeight: '700',
    marginBottom: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  productName: {
    fontSize: '1.125rem',
    fontWeight: '700',
    marginBottom: '0.5rem',
    color: colors.black,
    lineHeight: '1.4',
  },
  price: {
    fontSize: '1.5rem',
    fontWeight: '800',
    color: colors.black,
    marginBottom: '1rem',
    marginTop: 'auto', // Push to bottom if flex column
  },
  addButton: {
    width: '100%',
    padding: '0.875rem',
    backgroundColor: colors.black,
    borderRadius: colors.radiusFull,
    fontWeight: '600',
    color: colors.white,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    transition: colors.transition,
    cursor: 'pointer',
    border: 'none',
    boxShadow: colors.shadowMd,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
    backdropFilter: 'blur(5px)',
  },
  modalContent: {
    position: 'relative',
    maxWidth: '90%',
    maxHeight: '90%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    maxWidth: '100%',
    maxHeight: '85vh',
    objectFit: 'contain',
    borderRadius: '8px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
  },
  closeButton: {
    position: 'absolute',
    top: '-40px',
    right: 0,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '5px',
  },
};
