import { colors } from '@/shared/styles/theme';

export const headerStyles = {
  pokeball: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '3px solid #1f2937',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 2px 6px rgba(0,0,0,0.25)',
  },
  top: {
    flex: 1,
    backgroundColor: '#ef4444',
  },
  middle: {
    height: 6,
    backgroundColor: '#1f2937',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    width: 10,
    height: 10,
    borderRadius: '50%',
    backgroundColor: colors.white,
    border: '2px solid #1f2937',
  },
  bottom: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)', // Translucent for glass effect
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
    padding: '1rem 0',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    transition: colors.transition,
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: colors.black,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  logoAccent: {
    color: colors.yellowPrimary,
  },
  nav: {
    display: 'flex',
    gap: '2rem',
  },
  navLink: {
    color: colors.black,
    fontWeight: '500',
    fontSize: '1rem',
    transition: 'color 0.2s',
  },
  rightActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  cartButton: {
    position: 'relative',
    width: '40px',
    height: '40px',
    border: `2px solid ${colors.yellowPrimary}`,
    borderRadius: '8px',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.black,
    transition: 'all 0.2s',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  cartBadge: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    backgroundColor: '#ff4444',
    color: colors.white,
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75rem',
    fontWeight: 'bold',
  },
  loginButton: {
    padding: '0.5rem 1.5rem',
    backgroundColor: colors.yellowPrimary,
    border: `2px solid ${colors.yellowPrimary}`,
    borderRadius: '8px',
    fontWeight: '600',
    color: colors.black,
    transition: 'all 0.2s',
    textDecoration: 'none',
    display: 'inline-block',
  },
  userButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1.5rem',
    backgroundColor: colors.yellowPrimary,
    border: `2px solid ${colors.yellowPrimary}`,
    borderRadius: '8px',
    fontWeight: '600',
    color: colors.black,
    transition: 'all 0.2s',
    textDecoration: 'none',
  },
};
