import { colors } from './theme';

export const catalogStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '4rem 2rem',
    minHeight: '100vh',
  },
  header: {
    textAlign: 'center',
    marginBottom: '4rem',
  },
  title: {
    fontSize: '3rem',
    fontWeight: '800',
    marginBottom: '1rem',
    color: colors.black,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '1.125rem',
    color: colors.grayDark,
    marginBottom: '3rem',
    maxWidth: '600px',
    margin: '0 auto 3rem',
    lineHeight: '1.6',
  },
  searchContainer: {
    position: 'relative',
    maxWidth: '500px',
    margin: '0 auto 2.5rem',
  },
  searchIcon: {
    position: 'absolute',
    left: '1.25rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: colors.grayDark,
  },
  searchInput: {
    width: '100%',
    padding: '1.25rem 1.25rem 1.25rem 3.5rem',
    border: `2px solid ${colors.grayMedium}`,
    borderRadius: colors.radiusFull,
    fontSize: '1rem',
    outline: 'none',
    transition: colors.transition,
    backgroundColor: colors.white,
    boxShadow: colors.shadowSm,
    color: colors.black,
  },
  filters: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.75rem',
    flexWrap: 'wrap',
    marginBottom: '2rem',
  },
  filterButton: {
    padding: '0.625rem 1.5rem',
    backgroundColor: colors.white,
    border: `1px solid ${colors.grayMedium}`,
    borderRadius: colors.radiusFull,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: colors.grayDark,
    transition: colors.transition,
    cursor: 'pointer',
    boxShadow: colors.shadowSm,
  },
  filterButtonActive: {
    backgroundColor: colors.black,
    borderColor: colors.black,
    color: colors.white,
    transform: 'translateY(-1px)',
    boxShadow: colors.shadowMd,
  },
  productCount: {
    fontSize: '0.875rem',
    color: colors.grayDark,
    marginTop: '1.5rem',
    fontWeight: '500',
  },
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '2rem',
    paddingBottom: '4rem',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '400px',
  },
  loadingSpinner: {
    width: '48px',
    height: '48px',
    border: `4px solid ${colors.grayLight}`,
    borderTop: `4px solid ${colors.yellowPrimary}`,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    marginBottom: '1.5rem',
  },
  loadingText: {
    fontSize: '1rem',
    color: colors.grayDark,
    fontWeight: '500',
  },
  errorContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '400px',
    textAlign: 'center',
  },
  errorText: {
    fontSize: '1.125rem',
    color: colors.redError,
    marginBottom: '1.5rem',
    fontWeight: '500',
  },
  retryButton: {
    padding: '0.875rem 2rem',
    backgroundColor: colors.black,
    color: colors.white,
    border: 'none',
    borderRadius: colors.radiusFull,
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: colors.transition,
    boxShadow: colors.shadowMd,
  },
};
