import { colors } from './theme';

export const dashboardStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '2rem',
    minHeight: 'calc(100vh - 80px)',
  },
  welcomeSection: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '3rem',
    padding: '2rem',
    backgroundColor: colors.yellowLight,
    borderRadius: '20px',
    flexWrap: 'wrap',
    gap: '1rem',
  },
  welcomeContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  avatar: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: colors.yellowPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.black,
  },
  welcomeTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: '0.5rem',
  },
  highlight: {
    color: colors.yellowPrimary,
  },
  welcomeSubtitle: {
    fontSize: '1rem',
    color: '#666',
  },
  logoutButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    border: `2px solid ${colors.yellowPrimary}`,
    borderRadius: '12px',
    fontWeight: '600',
    color: colors.black,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  statsSection: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1.5rem',
    marginBottom: '3rem',
  },
  statCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.5rem',
    backgroundColor: colors.white,
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  statIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statContent: {
    display: 'flex',
    flexDirection: 'column',
  },
  statValue: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: colors.black,
  },
  statLabel: {
    fontSize: '0.875rem',
    color: '#666',
  },
  actionsSection: {
    marginBottom: '3rem',
  },
  sectionTitle: {
    fontSize: '1.75rem',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: '1.5rem',
  },
  actionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
  },
  actionCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '1.5rem',
    backgroundColor: colors.white,
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    textDecoration: 'none',
    color: colors.black,
    transition: 'transform 0.2s',
    cursor: 'pointer',
  },
  actionIcon: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    backgroundColor: colors.yellowPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.black,
  },
  actionLabel: {
    fontSize: '0.875rem',
    fontWeight: '600',
    textAlign: 'center',
  },
  accountSection: {
    marginBottom: '2rem',
  },
  accountCard: {
    backgroundColor: colors.white,
    borderRadius: '16px',
    padding: '2rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  accountRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 0',
    borderBottom: '1px solid #e5e5e5',
  },
  accountLabel: {
    fontSize: '1rem',
    color: '#666',
    fontWeight: '500',
  },
  accountValue: {
    fontSize: '1rem',
    color: colors.black,
    fontWeight: '600',
  },
  accountStatus: {
    fontSize: '0.875rem',
    padding: '0.25rem 0.75rem',
    backgroundColor: '#d4edda',
    color: '#155724',
    borderRadius: '20px',
    fontWeight: '600',
  },
  favoritesSection: {
    marginBottom: '3rem',
  },
  favoritesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1.5rem',
  },
  favoriteCard: {
    backgroundColor: colors.white,
    borderRadius: '16px',
    padding: '1rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    transition: 'transform 0.2s',
    cursor: 'pointer',
  },
  favoriteImage: {
    width: '100%',
    height: '200px',
    borderRadius: '12px',
    overflow: 'hidden',
    backgroundColor: colors.yellowLight,
    marginBottom: '0.75rem',
  },
  favoriteImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  favoriteInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  favoriteName: {
    fontSize: '1rem',
    fontWeight: '600',
    color: colors.black,
    margin: 0,
  },
  favoriteType: {
    fontSize: '0.875rem',
    color: '#666',
    margin: 0,
  },
  favoritePrice: {
    fontSize: '1.125rem',
    fontWeight: 'bold',
    color: colors.black,
    margin: 0,
    marginTop: '0.5rem',
  },
  emptyFavorites: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    backgroundColor: colors.white,
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  emptyIcon: {
    color: '#ccc',
    marginBottom: '1rem',
  },
  emptyText: {
    fontSize: '1rem',
    color: '#666',
    marginBottom: '1.5rem',
  },
  browseButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: colors.yellowPrimary,
    borderRadius: '12px',
    fontWeight: '600',
    color: colors.black,
    textDecoration: 'none',
    transition: 'transform 0.2s',
  },
};

