import { colors } from './theme';

export const homeStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '4rem 2rem',
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.2fr)',
    gap: '4rem',
    alignItems: 'center',
    marginBottom: '8rem',
    paddingTop: '2rem',
  },
  heroContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
    alignItems: 'flex-start',
  },
  banner: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.75rem',
    backgroundColor: colors.white,
    padding: '0.75rem 1.5rem',
    borderRadius: colors.radiusFull,
    fontSize: '0.875rem',
    fontWeight: '600',
    width: 'fit-content',
    boxShadow: colors.shadowSm,
    border: `1px solid ${colors.grayMedium}`,
    color: colors.grayDark,
  },
  heroTitle: {
    fontSize: '4.5rem',
    fontWeight: '800',
    lineHeight: '1.1',
    letterSpacing: '-0.02em',
    color: colors.black,
    backgroundImage: `linear-gradient(135deg, ${colors.black} 0%, #4a4a4a 100%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  highlight: {
    color: colors.yellowPrimary,
    WebkitTextFillColor: colors.yellowPrimary, // Override gradient for highlight
    position: 'relative',
    display: 'inline-block',
    zIndex: 1,
  },
  heroDescription: {
    fontSize: '1.25rem',
    color: colors.grayDark,
    lineHeight: '1.7',
    maxWidth: '540px',
    fontWeight: '400',
  },
  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '1rem 2.5rem',
    background: colors.yellowPrimary,
    borderRadius: colors.radiusFull,
    fontWeight: '700',
    color: colors.black,
    fontSize: '1.125rem',
    transition: colors.transition,
    textDecoration: 'none',
    boxShadow: '0 4px 6px -1px rgba(255, 214, 10, 0.4), 0 2px 4px -1px rgba(255, 214, 10, 0.2)',
    border: 'none',
    cursor: 'pointer',
  },
  secondaryButton: {
    padding: '1rem 2.5rem',
    backgroundColor: colors.white,
    border: `2px solid ${colors.grayMedium}`,
    borderRadius: colors.radiusFull,
    fontWeight: '600',
    color: colors.black,
    fontSize: '1.125rem',
    cursor: 'pointer',
    transition: colors.transition,
  },
  stats: {
    display: 'flex',
    gap: '3rem',
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: `1px solid ${colors.grayMedium}`,
    width: '100%',
  },
  stat: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    alignItems: 'flex-start',
  },
  statNumber: {
    fontSize: '2rem',
    fontWeight: '800',
    color: colors.black,
    lineHeight: 1,
  },
  statLabel: {
    fontSize: '0.875rem',
    color: colors.grayDark,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  heroImage: {
    position: 'relative',
    borderRadius: '2rem',
    width: '100%',
    boxShadow: colors.shadowXl,
    overflow: 'hidden', // Ensure image stays within radius
    background: colors.white,
    padding: '1rem', // Frame effect
  },
  image: {
    width: '100%',
    height: 'auto',
    aspectRatio: '1',
    display: 'block',
    borderRadius: '1.5rem',
    objectFit: 'cover',
  },
  bestSellerTag: {
    position: 'absolute',
    top: '30px',
    right: '30px',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    backdropFilter: 'blur(8px)',
    padding: '1rem 1.25rem',
    borderRadius: colors.radiusLg,
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    zIndex: 2,
    boxShadow: colors.shadowLg,
  },
  bestSellerLabel: {
    fontSize: '0.75rem',
    fontWeight: '700',
    color: colors.grayDark,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  bestSellerProduct: {
    fontSize: '1rem',
    fontWeight: '800',
    color: colors.black,
  },
  popularSection: {
    marginBottom: '8rem',
  },
  sectionHeader: {
    textAlign: 'center',
    marginBottom: '4rem',
    maxWidth: '700px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  sectionBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: colors.yellowLight,
    color: colors.yellowDark,
    padding: '0.5rem 1rem',
    borderRadius: colors.radiusFull,
    fontSize: '0.875rem',
    fontWeight: '700',
    marginBottom: '1.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  sectionTitle: {
    fontSize: '3rem',
    fontWeight: '800',
    marginBottom: '1rem',
    color: colors.black,
    letterSpacing: '-0.02em',
  },
  sectionDescription: {
    fontSize: '1.125rem',
    color: colors.grayDark,
    lineHeight: '1.6',
  },
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '2rem',
    marginBottom: '3rem',
  },
  viewAllButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    margin: '0 auto',
    padding: '1rem 3rem',
    backgroundColor: colors.black, // Dark button for contrast
    border: 'none',
    borderRadius: colors.radiusFull,
    fontWeight: '600',
    color: colors.white,
    fontSize: '1rem',
    width: 'fit-content',
    textDecoration: 'none',
    transition: colors.transition,
    boxShadow: colors.shadowMd,
  },
  featuresSection: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '2rem',
    marginTop: '6rem',
    paddingTop: '6rem',
    borderTop: `1px solid ${colors.grayMedium}`,
  },
  featureCard: {
    textAlign: 'center',
    padding: '2rem',
    backgroundColor: colors.white,
    borderRadius: colors.radiusLg,
    boxShadow: colors.shadowSm,
    transition: colors.transition,
  },
  featureIcon: {
    width: '72px',
    height: '72px',
    backgroundColor: colors.yellowLight,
    borderRadius: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1.5rem',
    color: colors.yellowDark,
  },
  featureTitle: {
    fontSize: '1.25rem',
    fontWeight: '700',
    marginBottom: '0.75rem',
    color: colors.black,
  },
  featureDescription: {
    fontSize: '0.875rem',
    color: colors.grayDark,
    lineHeight: '1.6',
  },
};

