import { colors } from '@/shared/styles/theme';

export const cartStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '2rem',
    minHeight: 'calc(100vh - 80px)',
  },
  header: {
    marginBottom: '2rem',
  },
  backButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: colors.black,
    textDecoration: 'none',
    marginBottom: '1rem',
    fontWeight: '500',
    transition: 'color 0.2s',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    color: colors.black,
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  cartContent: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '2rem',
  },
  itemsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  cartItem: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr auto auto auto',
    gap: '1rem',
    alignItems: 'center',
    padding: '1.5rem',
    backgroundColor: colors.white,
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  itemImage: {
    width: '100px',
    height: '100px',
    borderRadius: '12px',
    overflow: 'hidden',
    backgroundColor: colors.yellowLight,
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  itemDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  itemName: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: colors.black,
    margin: 0,
  },
  itemType: {
    fontSize: '0.875rem',
    color: '#666',
    margin: 0,
  },
  itemPrice: {
    fontSize: '0.875rem',
    color: '#666',
    margin: 0,
  },
  quantityControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    backgroundColor: colors.yellowLight,
    padding: '0.5rem',
    borderRadius: '8px',
  },
  quantityButton: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.yellowPrimary,
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    color: colors.black,
    transition: 'transform 0.2s',
  },
  quantity: {
    fontSize: '1rem',
    fontWeight: '600',
    minWidth: '24px',
    textAlign: 'center',
  },
  itemTotal: {
    textAlign: 'right',
  },
  totalPrice: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    color: colors.black,
    margin: 0,
  },
  removeButton: {
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: '2px solid #ff4444',
    borderRadius: '8px',
    color: '#ff4444',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  summarySection: {
    position: 'sticky',
    top: '100px',
    height: 'fit-content',
  },
  summaryCard: {
    backgroundColor: colors.white,
    borderRadius: '16px',
    padding: '2rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  summaryTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: '1.5rem',
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    fontSize: '1rem',
    color: '#666',
  },
  freeShipping: {
    color: '#4CAF50',
    fontWeight: '600',
  },
  divider: {
    height: '1px',
    backgroundColor: '#e5e5e5',
    margin: '1.5rem 0',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1.5rem',
  },
  totalLabel: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    color: colors.black,
  },
  totalAmount: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: colors.black,
  },
  checkoutButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '1rem 2rem',
    background: colors.orangeGradient,
    borderRadius: '12px',
    fontWeight: '600',
    color: colors.black,
    fontSize: '1rem',
    border: 'none',
    cursor: 'pointer',
    marginBottom: '1rem',
    transition: 'transform 0.2s',
  },
  continueShopping: {
    display: 'block',
    textAlign: 'center',
    color: colors.black,
    textDecoration: 'none',
    fontWeight: '500',
    padding: '0.75rem',
    border: `2px solid ${colors.yellowPrimary}`,
    borderRadius: '12px',
    transition: 'all 0.2s',
  },
  emptyCart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    textAlign: 'center',
  },
  emptyIcon: {
    color: '#ccc',
    marginBottom: '1rem',
  },
  emptyTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: '0.5rem',
  },
  emptyText: {
    fontSize: '1rem',
    color: '#666',
    marginBottom: '2rem',
  },
  shopButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '1rem 2rem',
    background: colors.orangeGradient,
    borderRadius: '12px',
    fontWeight: '600',
    color: colors.black,
    fontSize: '1rem',
    textDecoration: 'none',
    transition: 'transform 0.2s',
  },
};

