import { colors } from '@/shared/styles/theme';

export const authStyles = {
  container: {
    minHeight: 'calc(100vh - 80px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    backgroundColor: colors.white,
  },
  card: {
    width: '100%',
    maxWidth: '450px',
    backgroundColor: colors.white,
    borderRadius: '20px',
    padding: '3rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.1)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '2rem',
  },
  banner: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: colors.yellowPrimary,
    padding: '0.5rem 1rem',
    borderRadius: '20px',
    fontSize: '0.875rem',
    fontWeight: '600',
    marginBottom: '1rem',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    lineHeight: '1.2',
    color: colors.black,
    marginBottom: '0.5rem',
  },
  highlight: {
    backgroundColor: colors.yellowPrimary,
    padding: '0 0.5rem',
    borderRadius: '4px',
  },
  description: {
    fontSize: '1rem',
    color: '#666',
    lineHeight: '1.6',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  label: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    color: colors.black,
  },
  icon: {
    color: colors.yellowPrimary,
  },
  input: {
    padding: '1rem',
    border: '2px solid #e5e5e5',
    borderRadius: '12px',
    fontSize: '1rem',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  errorText: {
    color: colors.redError,
    fontSize: '0.8rem',
    marginTop: '0.2rem',
  },
  options: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.875rem',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#666',
    cursor: 'pointer',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: colors.yellowPrimary,
  },
  forgotLink: {
    color: colors.black,
    fontWeight: '600',
    transition: 'color 0.2s',
  },
  submitButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '1rem 2rem',
    background: colors.orangeGradient,
    borderRadius: '12px',
    fontWeight: '600',
    color: colors.black,
    fontSize: '1rem',
    transition: 'transform 0.2s',
    border: 'none',
    cursor: 'pointer',
    marginTop: '0.5rem',
    textDecoration: 'none',
  },
  footer: {
    marginTop: '2rem',
    textAlign: 'center',
  },
  footerText: {
    fontSize: '0.875rem',
    color: '#666',
  },
  link: {
    color: colors.black,
    fontWeight: '600',
    transition: 'color 0.2s',
  },
  row: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
  },
};

